name: CI

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

on:
  merge_group:
  pull_request:

jobs:
    build-and-generate:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          example_path: [
            "functions/filter",
            "functions/filter-map",
            "functions/flat-map",
            "functions/map",
            "functions/ref-state",
            "functions/update-state",
            "use-cases/bank-processing",
            "use-cases/http-callout",
            "use-cases/word-counter",
          ]
          ssdk-version: [ssdk-preview6]
      steps:
        - name: Checkout
          uses: actions/checkout@v3
  
        - name: Install stable CLI and start Fluvio cluster
          timeout-minutes: 10
          run: |
            curl -fsS https://hub.infinyon.cloud/install/install.sh | bash

        - name: Setup fluvio bin path
          run:  echo "~/.fluvio/bin" >> $GITHUB_PATH

        - name: Setup fvm bin path
          run:  echo "~/.fvm/bin" >> $GITHUB_PATH

        - name: Install SSDK version
          run: |
            fvm install ${{ matrix.ssdk-version }}

        - name: Run ssdk setup
          run: |
            ssdk setup
        
        - name: Run ssdk generate
          working-directory: ./${{ matrix.example_path }}
          run: |
            ssdk generate
        
        - name: Run ssdk build
          working-directory: ./${{ matrix.example_path }}
          run: |
            ssdk build
